import { Work_Sans } from "next/font/google"
import { Navbar } from "@/components"

import "./globals.css"

const inter = Work_Sans({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        Footer
      </body>
    </html>
  )
}
